src/der_duemmste/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash

from .model.user import User
from . import db, login_manager

auth_bp = Blueprint("auth", __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for("main.index"))
        else:
            flash("Invalid username or password", "error")
    return render_template("login.html")


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        try:
            new_user = User(username=username, password=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()
            return render_template('partials/user_item.html', user=new_user)
        except IntegrityError:
            db.session.rollback()
            flash("Username already exists", "error")


@auth_bp.route("/delete_user/<int:user_id>", methods=["DELETE"])
def delete_user(user_id: int):
    user = User.query.get(user_id)
    if not user:
        return {"error": "User not found"}, 404
    db.session.delete(user)
    db.session.commit()
    return '', 200

src/der_duemmste/routes/questions.py
from flask import Blueprint, render_template, request, jsonify
from sqlalchemy.exc import IntegrityError
from der_duemmste.extensions import db

from der_duemmste.model.question import Question

questions_bp = Blueprint('questions', __name__)


@questions_bp.route('/', methods=['POST'])
def create_question():

    question_text = request.form['question']
    question_answer = request.form['answer']

    if not question_text or not question_answer:
        return jsonify({'error': 'Invalid question form input'}), 400

    try:
        new_question = Question(question_text, question_answer)
        db.session.add(new_question)
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return jsonify({'error': 'Question already exists'}), 400

    return render_template('partials/question_item.html', question=new_question)


@questions_bp.route('/<int:question_id>', methods=['GET'])
def show_question(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('partials/question_item.html', question=question)


@questions_bp.route('/<int:question_id>/edit', methods=['GET'])
def edit_question(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('partials/question_edit.html', question=question)


@questions_bp.route('/<int:question_id>/update', methods=['PUT', 'PATCH'])
def update_question(question_id):
    question = Question.query.get_or_404(question_id)
    question_text = request.form['question']
    question_answer = request.form['answer']
    if not question_text or not question_answer:
        return jsonify({'error': 'Invalid question form input'}), 400

    question.question = question_text
    question.answer = question_answer
    db.session.commit()
    return render_template('partials/question_item.html', question=question)


@questions_bp.route('/<int:question_id>/delete', methods=['DELETE'])
def delete_question(question_id):
    question = Question.query.get(question_id)
    if not question:
        return jsonify({'error': 'Question not found'}), 404
    db.session.delete(question)
    db.session.commit()
    return '', 200

src/der_duemmste/routes/user.py
from flask import Blueprint, render_template, request, jsonify, flash
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash
from der_duemmste.extensions import db

from der_duemmste.model.user import User

user_bp = Blueprint('user', __name__)


@user_bp.route("/register", methods=["POST"])
def register_user():
    if not request.form.get("username") or not request.form.get("password"):
        return jsonify({"error": "Username and password required"}), 400
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        try:
            new_user = User(username=username, password=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()
            return render_template('partials/user_item.html', user=new_user)
        except IntegrityError:
            db.session.rollback()
            flash("Username already exists", "error")
            return jsonify({"error": "Username already exists"}), 400


@user_bp.route("/<int:user_id>", methods=["GET"])
def show_user(user_id: int):
    user = User.query.get_or_404(user_id)
    return render_template('partials/user_item.html', user=user)


@user_bp.route("/<int:user_id>/edit", methods=["GET"])
def edit_user(user_id: int):
    user = User.query.get_or_404(user_id)
    return render_template('partials/user_edit.html', user=user)


@user_bp.route("/<int:user_id>/update", methods=["PUT", "PATCH"])
def update_user(user_id: int):
    user = User.query.get_or_404(user_id)
    try:
        username = request.form.get("username")
        remaining_lives = request.form.get("remaining_lives")
        new_password = request.form.get("password", "").strip()

        user.username = username
        if new_password:
            user.password = generate_password_hash(new_password)

        user.remaining_lives = remaining_lives
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return jsonify({"error": "Username already exists"}), 400
    return render_template('partials/user_item.html', user=user)


@user_bp.route("/<int:user_id>/delete", methods=["DELETE"])
def delete_user(user_id: int):
    user = User.query.get(user_id)
    if not user:
        return {"error": "User not found"}, 404
    db.session.delete(user)
    db.session.commit()
    return '', 200

src/der_duemmste/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Der Dümmste fliegt</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">   
    <link rel="stylesheet" href={{ url_for('static', filename='css/style.css') }}>
    <script src="{{ url_for('static', filename='js/htmx.min.js') }}"></script>
</head>
<body class="bg-gray-800 text-white flex flex-col min-h-screen">
    {% include 'partials/header.html' %}
    <main class="flex-grow container mx-auto p-4">
        {% if current_user.is_authenticated %}
        {% block content %}{% endblock %}
        {% else %}
        {% include 'partials/access_denied.html' %}
        {% endif %}
    </main>
    {% include 'partials/footer.html' %}

</body>

src/der_duemmste/templates/index.html
{% extends "base.html" %}
{% block title %}Der Dümmste fliegt{% endblock %}
{% block content %}
    <section class="text-center">
        <h1 class="text-3xl font-bold">Der Dümmste fliegt</h1>
        <p class="text-lg mt-4">Wir beantworten reihum Fragen. 120 Sekunden pro Runde. Am Ende wird der Dümmste gewählt. Du bekommst eine Browser Source. Verwende selbst den Discord </p>
        <div class="mt-8">
            <h2 class="text-xl font-bold mb-8">Hallo {{current_user.username}}!</h2>
            {% if current_user.is_admin %}
            {% else %}
            {% endif %}
        </div>
    </section>
{% endblock %}

src/der_duemmste/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Der Dümmste fliegt</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">   
    <link rel="stylesheet" href={{ url_for('static', filename='css/style.css') }}>
</head>
<body class="bg-gray-800 text-white flex flex-col min-h-screen">

<div class="w-lg mx-auto mt-10 bg-gray-600 p-6 rounded-lg shadow-lg">
    <h2 class="text-2xl mb-4 font-bold text-center">Login</h2>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="bg-{{category}}-500 text-white text-sm p-2 mb-2 rounded">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <form method="POST" action="{{ url_for('auth.login') }}" class="space-y-2">
        <div>
            <label for="username" class="block text-sm font-medium text-gray-200">
                Username
            </label>
            <input type="text" id="username" name="username" 
                    placeholder="username" required class="
                    mt-1 block w-full px-3 py-2 bg-gray-700 border 
                    border-gray-600 rounded-md shadow-sm focus:outline-none 
                    focus:ring-blue-500 focus:border-blue-500 text-white
                ">
        </div>
        <div>
            <label for="password" class="block text-sm font-medium text-gray-200">
                Password
            </label>
            <input type="password" id="password" name="password" 
                    placeholder="********" required class="
                    appearance-none
                    mt-1 block w-full px-3 py-2 bg-gray-700 border 
                    border-gray-600 rounded-md shadow-sm focus:outline-none 
                    focus:ring-blue-500 focus:border-blue-500 
                ">
        </div>
        <button type="submit" class="mt-6 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Login
        </button>
    </form>
</div>

src/der_duemmste/templates/player_overview.html
{% extends "base.html" %}
{% block title %}Player Overview{% endblock %}
{% block content %}
    <section class="text-center">
        <h1 class="text-3xl font-bold">Player Overview</h1>
        {% if current_user.is_admin %}
        <!-- Add Question Form -->
        <form 
            hx-post="{{ url_for('user.register_user') }}" 
            hx-target="#user-list" 
            hx-swap="afterbegin"
            hx-on::after-request="setTimeout(() => this.reset(), 50)"
            class="max-w-xl mx-auto mt-6 mb-6 bg-gray-600 p-4 rounded-lg shadow-lg">
        
            <label for="username" class="block text-sm font-medium text-gray-200">
                Player Name:
            </label>
            <input type="text" id="username" name="username" required
                   class="mt-1 block w-full px-3 py-2 bg-gray-700 border 
                   border-gray-600 rounded-md shadow-sm focus:ring-blue-500 
                   focus:border-blue-500 text-white">

            <label for="password" class="block text-sm font-medium text-gray-200 mt-4">
                Password:
            </label>
            <input type="text" id="password" name="password" required
                   class="mt-1 block w-full px-3 py-2 bg-gray-700 border 
                   border-gray-600 rounded-md shadow-sm focus:ring-blue-500 
                   focus:border-blue-500 text-white">

            <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 
                text-white font-bold py-2 px-4 rounded mt-4">
                Add Player 
            </button>
        </form>

        <!-- Questions Table -->
        {% include 'partials/user_list.html' %}
        {% else %}
        <h2 class="mt-6 text-xl font-bold">There's nothing to see here</h2>
        {% endif %}
    </section>
{% endblock %}

src/der_duemmste/templates/question_overview.html
{% extends "base.html" %}
{% block title %}Question Overview {% endblock %}
{% block content %}
    <section class="text-center">
        <h1 class="text-3xl font-bold">Question Overview</h1>
        {% if current_user.is_admin %}
        <!-- Add Question Form -->
        <form 
            hx-post="{{ url_for('questions.create_question') }}" 
            hx-target="#question-list" 
            hx-swap="afterbegin"
            hx-on::after-request="setTimeout(() => this.reset(), 50)"
            class="max-w-xl mx-auto mt-6 mb-6 bg-gray-600 p-4 rounded-lg shadow-lg">
        
            <label for="question" class="block text-sm font-medium text-gray-200">
                Question:
            </label>
            <input type="text" id="question" name="question" required
                   class="mt-1 block w-full px-3 py-2 bg-gray-700 border 
                   border-gray-600 rounded-md shadow-sm focus:ring-blue-500 
                   focus:border-blue-500 text-white">

            <label for="answer" class="block text-sm font-medium text-gray-200 mt-4">
                Answer:
            </label>
            <input type="text" id="answer" name="answer" required
                   class="mt-1 block w-full px-3 py-2 bg-gray-700 border 
                   border-gray-600 rounded-md shadow-sm focus:ring-blue-500 
                   focus:border-blue-500 text-white">

            <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 
                text-white font-bold py-2 px-4 rounded mt-4">
                Add Question
            </button>
        </form>

        <!-- Questions Table -->
        {% set endpoint = 'main.list_questions' %}
        {% set target = '#questions-container' %}
        {% include 'partials/question_list.html' %}
        {% else %}
        <h2 class="mt-6 text-xl font-bold">There's nothing to see here</h2>
        {% endif %}
    </section>
{% endblock %}