src/der_duemmste/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash

from .model.user import User
from . import db, login_manager

auth_bp = Blueprint("auth", __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for("main.index"))
        else:
            flash("Invalid username or password", "error")
    return render_template("login.html")


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        try:
            new_user = User(username=username, password=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()
            return render_template('partials/user_item.html', user=new_user)
        except IntegrityError:
            db.session.rollback()
            flash("Username already exists", "error")


@auth_bp.route("/delete_user/<int:user_id>", methods=["DELETE"])
def delete_user(user_id: int):
    user = User.query.get(user_id)
    if not user:
        return {"error": "User not found"}, 404
    db.session.delete(user)
    db.session.commit()
    return '', 200

src/der_duemmste/routes.py
from flask import Blueprint, render_template, request, jsonify
from sqlalchemy.exc import IntegrityError
from .model.question import Question
from .model.user import User
from . import db

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    return render_template('index.html')


@main_bp.route('/test')
def test():
    return render_template('base.html')


@main_bp.route('/player_overview', methods=['GET'])
def list_players():
    page = request.args.get('page', 1, type=int)
    per_page = 20
    pagination = User.query.order_by(User.id.desc()).filter_by(is_admin=False).paginate(
        page=page, per_page=per_page, error_out=False
    )
    if request.headers.get('HX-Request'):
        return render_template(
            'partials/user_list.html',
            users=pagination.items,
            pagination=pagination
        )
    return render_template('player_overview.html')


@main_bp.route('/question_overview', methods=['GET'])
def list_questions():
    page = request.args.get('page', 1, type=int)
    per_page = 20
    pagination = Question.query.order_by(Question.id.desc()).paginate(
        page=page, per_page=per_page, error_out=False
    )

    if request.headers.get('HX-Request'):
        return render_template(
            'partials/question_list.html',
            questions=pagination.items,
            pagination=pagination
        )

    return render_template('question_overview.html',
                           questions=pagination.items,
                           pagination=pagination)


@main_bp.route('/add_question', methods=['POST'])
def add_question():
    question_text = request.form['question']
    question_answer = request.form['answer']

    if not question_text or not question_answer:
        return jsonify({'error': 'Invalid question form input'}), 400

    try:
        new_question = Question(question_text, question_answer)
        db.session.add(new_question)
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return jsonify({'error': 'Question already exists'}), 400
    return render_template('partials/question_item.html', question=new_question)


@main_bp.route('/delete_question/<int:question_id>', methods=['DELETE'])
def delete_question(question_id):
    question = Question.query.get(question_id)
    if not question:
        return jsonify({'error': 'Question not found'}), 404
    db.session.delete(question)
    db.session.commit()
    return '', 200

src/der_duemmste/routes/questions.py
from flask import Blueprint, render_template, request, jsonify
from sqlalchemy.exc import IntegrityError
from der_duemmste.extensions import db

from der_duemmste.model.question import Question

questions_bp = Blueprint('questions', __name__)


@questions_bp.route('/', methods=['POST'])
def create_question():

    question_text = request.form['question']
    question_answer = request.form['answer']

    if not question_text or not question_answer:
        return jsonify({'error': 'Invalid question form input'}), 400

    try:
        new_question = Question(question_text, question_answer)
        db.session.add(new_question)
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return jsonify({'error': 'Question already exists'}), 400

    return render_template('partials/question_item.html', question=new_question)


@questions_bp.route('/<int:question_id>', methods=['GET'])
def show_question(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('partials/question_item.html', question=question)


@questions_bp.route('/<int:question_id>/edit', methods=['GET'])
def edit_question(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('partials/question_edit.html', question=question)


@questions_bp.route('/<int:question_id>/update', methods=['PUT', 'PATCH'])
def update_question(question_id):
    question = Question.query.get_or_404(question_id)
    question_text = request.form['question']
    question_answer = request.form['answer']
    if not question_text or not question_answer:
        return jsonify({'error': 'Invalid question form input'}), 400

    question.question = question_text
    question.answer = question_answer
    db.session.commit()
    return render_template('partials/question_item.html', question=question)


@questions_bp.route('/<int:question_id>/delete', methods=['DELETE'])
def delete_question(question_id):
    question = Question.query.get(question_id)
    if not question:
        return jsonify({'error': 'Question not found'}), 404
    db.session.delete(question)
    db.session.commit()
    return '', 200

src/der_duemmste/routes/user.py
from flask import Blueprint, render_template, request, jsonify, flash
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash
from der_duemmste.extensions import db

from der_duemmste.model.user import User

user_bp = Blueprint('user', __name__)


@user_bp.route("/register", methods=["POST"])
def register_user():
    if not request.form.get("username") or not request.form.get("password"):
        return jsonify({"error": "Username and password required"}), 400
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        try:
            new_user = User(username=username, password=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()
            return render_template('partials/user_item.html', user=new_user)
        except IntegrityError:
            db.session.rollback()
            flash("Username already exists", "error")
            return jsonify({"error": "Username already exists"}), 400


@user_bp.route("/<int:user_id>", methods=["GET"])
def show_user(user_id: int):
    user = User.query.get_or_404(user_id)
    return render_template('partials/user_item.html', user=user)


@user_bp.route("/<int:user_id>/edit", methods=["GET"])
def edit_user(user_id: int):
    user = User.query.get_or_404(user_id)
    return render_template('partials/user_edit.html', user=user)


@user_bp.route("/<int:user_id>/update", methods=["PUT", "PATCH"])
def update_user(user_id: int):
    user = User.query.get_or_404(user_id)
    try:
        username = request.form.get("username")
        remaining_lives = request.form.get("remaining_lives")
        new_password = request.form.get("password", "").strip()

        user.username = username
        if new_password:
            user.password = generate_password_hash(new_password)

        user.remaining_lives = remaining_lives
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return jsonify({"error": "Username already exists"}), 400
    return render_template('partials/user_item.html', user=user)


@user_bp.route("/<int:user_id>/delete", methods=["DELETE"])
def delete_user(user_id: int):
    user = User.query.get(user_id)
    if not user:
        return {"error": "User not found"}, 404
    db.session.delete(user)
    db.session.commit()
    return '', 200

src/der_duemmste/templates/partials/access_denied.html
    <section class="text-center">
        <h1 class="text-3xl font-bold">No Access Just Yet</h1>
        <div class="mt-8">
            <h2 class="text-xl font-bold mb-8">Please Login</h2>
            <button>
                <a href="{{ url_for('auth.login') }}"
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold mt-10 py-2 px-4 rounded">
                    Login
                </a>
            </button>
    </section>

src/der_duemmste/templates/partials/footer.html
<footer class="bg-gray-800 p-4 text-center mt-auto">
    <p class="text-sm">Free Software licensed under GPL v3.0</p>
</footer>

src/der_duemmste/templates/partials/header.html
<header class="bg-gray-600 p-4 text-center">
    <nav>
        <div class="flex justify-between items-center">
            <h1 class="text-3xl font-bold">Don't show this!</h1>
            <ul class="flex justify-end">
                {% if current_user.is_authenticated %}
                {% if current_user.is_admin %}
                <li class="mr-6">
                    <a href="{{ url_for('main.list_questions') }}"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                    >
                        Questions
                    </a>
                </li>
                <li class="mr-6">
                    <a href="{{ url_for('main.list_players') }}"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                    >
                        Players
                    </a>
                </li>
                    {% endif %}
                <li class="mr-6">
                    <a href="{{ url_for('auth.logout') }}"
                        class="bg-gray-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
                    >
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="mr-6">
                    <a href="{{ url_for('auth.login') }}"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                    >
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

src/der_duemmste/templates/partials/pagination.html
{# partial/pagination.html #}
{% if pagination.has_prev %}
<button
    hx-get="{{ url_for(endpoint, page=pagination.prev_num) }}"
    hx-target="{{ target }}"
    hx-swap="innerHTML"
    class="bg-gray-700 text-white py-2 px-4 rounded hover:bg-gray-600"
>
    Previous
</button>
{% endif %}

<span>Page {{ pagination.page }} of {{ pagination.pages }}</span>

{% if pagination.has_next %}
<button
    hx-get="{{ url_for(endpoint, page=pagination.next_num) }}"
    hx-target="{{ target }}"
    hx-swap="innerHTML"
    class="bg-gray-700 text-white py-2 px-4 rounded hover:bg-gray-600"
>
    Next
</button>
{% endif %}

src/der_duemmste/templates/partials/question_edit.html
<tr 
    hx-trigger="cancel"
    hx-get="{{ url_for('questions.show_question', question_id=question.id) }}"
    id="question-{{ question.id }}">
    <td class="py-2 px-4 border-b border-gray-700 text-left w-10">{{ question.id }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">
        <input
            type="text"
            name="question"
            value="{{ question.question }}"
            class="bg-gray-600 text-white w-full border border-gray-500 rounded"
        >
    </td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">
        <input
            type="text"
            name="answer"
            value="{{ question.answer }}"
            class="bg-gray-600 text-white w-full border border-gray-500 rounded"
        >
    </td>
    <td class="py-2 px-4 border-b border-gray-700 text-center">
        <button
            hx-put="{{ url_for('questions.update_question', question_id=question.id) }}"
            hx-include="closest tr"
            class="bg-green-400 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
        >
            Save
        </button>

        <button
            hx-get="{{ url_for('questions.show_question', question_id=question.id) }}"
            class="bg-gray-400 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300"
        >
            Cancel
        </button>
    </td>
</tr>

src/der_duemmste/templates/partials/question_item.html
<tr id="question-{{ question.id }}">
    <td class="py-2 px-4 border-b border-gray-700 text-left w-10">{{ question.id }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">{{ question.question }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">{{ question.answer }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-center">
        <!-- hx-target="#question-{{ question.id }}"  -->
        <!-- hx-swap="outerHTML transition:true" -->
        <button
            hx-get="{{ url_for('questions.edit_question', question_id=question.id) }}"
            hx-target="#question-{{ question.id }}"
            hx-trigger="click"
            class="bg-emerald-400 hover:bg-emerald-600 text-white font-bold py-2 px-4 rounded transition duration-300"
        >
            Edit 
        </button>
        <button
            hx-delete="{{ url_for('questions.delete_question', question_id=question.id) }}"
            hx-target="closest tr"
            hx-swap="outerHTML transition:true"
            hx-confirm="Do you want to delete?"
            class="bg-red-400 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300"
        >
            Delete
        </button>
    </td>
</tr>

src/der_duemmste/templates/partials/question_list.html
<div class="mt-10" id="questions-container">
    <table class="min-w-full bg-gray-900 text-white border border-gray-600 rounded-lg overflow-hidden">
        <thead>
            <tr>
                <th class="py-2 px-4 border-b border-gray-600 text-left w-10">ID</th>
                <th class="py-2 px-4 border-b border-gray-600 text-left">Question</th>
                <th class="py-2 px-4 border-b border-gray-600 text-left">Answer</th>
                <th class="py-2 px-4 border-b border-gray-600 text-center">Actions</th>
            </tr>
        </thead>
        <tbody 
            id="question-list" 
            hx-target="closest tr" 
            hx-swap="outerHTML">
            {% for question in questions %}
                {% include 'partials/question_item.html' %}
            {% endfor %}
        </tbody>
    </table>
    <div class="flex justify-between mt-4">
        {% include 'partials/pagination.html' %}
    </div>
</div>

src/der_duemmste/templates/partials/user_edit.html
<tr 
    hx-trigger="cancel"
    hx-get="{{ url_for('user.show_user', user_id=user.id) }}"
    id="user-{{ user.id }}">
    <td class="py-2 px-4 border-b border-gray-700 text-left w-10">{{ user.id }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">
        <input
            type="text"
            name="username"
            value="{{ user.username }}"
            class="px-2 py-1 bg-gray-600 text-white w-full border border-gray-500 rounded"
        >
    </td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">
        <input
            type="password"
            name="password"
            placeholder="leave blank to keep"
            class="px-2 py-1 bg-gray-600 text-white w-full border border-gray-500 rounded"
        >
    </td>

    <td class="py-2 px-4 border-b border-gray-700 text-left">
        <input
            type="text"
            name="remaining_lives"
            value="{{ user.remaining_lives }}"
            class="px-2 py-1 bg-gray-600 text-white w-[30px] border border-gray-500 rounded"
        >
    </td>
    <td class="py-2 px-4 border-b border-gray-700 text-center">
        <button
            hx-put="{{ url_for('user.update_user', user_id=user.id) }}"
            hx-include="closest tr"
            class="bg-green-400 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
        >
            Save
        </button>

        <button
            hx-get="{{ url_for('user.show_user', user_id=user.id) }}"
            class="bg-gray-400 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300"
        >
            Cancel
        </button>
    </td>
</tr>

src/der_duemmste/templates/partials/user_item.html
<tr id="user-{{ user.id }}">
    <td class="py-2 px-4 border-b border-gray-700 text-left w-10">{{ user.id }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">{{ user.username }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">**********</td>
    <td class="py-2 px-4 border-b border-gray-700 text-left">{{ user.remaining_lives }}</td>
    <td class="py-2 px-4 border-b border-gray-700 text-center">
        <button
            hx-get="{{ url_for('user.edit_user', user_id=user.id) }}"
            hx-target="#user-{{ user.id }}"
            hx-trigger="click"
            class="bg-emerald-400 hover:bg-emerald-600 text-white font-bold py-2 px-4 rounded transition duration-300"
        >
            Edit 
        </button>
        <button
            hx-delete="{{ url_for('user.delete_user', user_id=user.id) }}"
            hx-target="closest tr"
            hx-swap="outerHTML transition:true"
            hx-confirm="Do you want to delete the user?"
            class="danger btn bg-red-400 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300"
        >
            Delete
        </button>
    </td>
</tr>

src/der_duemmste/templates/partials/user_list.html
<div class="mt-10" id="user-container">
    <table class="min-w-full bg-gray-900 text-white border border-gray-600 rounded-lg overflow-hidden">
        <thead>
            <tr>
                <th class="py-2 px-4 border-b border-gray-600 text-left w-10">ID</th>
                <th class="py-2 px-4 border-b border-gray-600 text-left">Player Name</th>
                <th class="py-2 px-4 border-b border-gray-600 text-left">Pass</th>
                <th class="py-2 px-4 border-b border-gray-600 text-left">Remaining Lives</th>
                <th class="py-2 px-4 border-b border-gray-600 text-center">Actions</th>
            </tr>
        </thead>
        <tbody 
            id="user-list"
            hx-target="closest tr"
            hx-swap="outerHTML">
            {% for user in users %}
                {% include 'partials/user_item.html' %}
            {% endfor %}
        </tbody>
    </table>
    <div class="flex justify-between mt-4">
        {% include 'partials/pagination.html' %}
    </div>
</div>